import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import UserProvider from "../components/UserProvider";
import ThemeProvider from "@/components/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProvider>
        <UserProvider>
          <body
            className={`${inter.className} flex min-h-screen flex-col p-4 sm:p-12 max-w-3xl mx-auto justify-between`}
          >
            <Nav />
            <main className="flex-1 mb-20">{children}</main>
            <Footer />
          </body>
        </UserProvider>
      </ThemeProvider>
    </html>
  );
}
