import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import UserProvider from "../components/UserProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex min-h-screen flex-col p-4 sm:p-12 max-w-2xl mx-auto`}
      >
        <UserProvider>
          <Nav />
          <main>{children}</main>
        </UserProvider>
      </body>
    </html>
  );
}
